### ISSUE TITLE
Clean up stylesheets

### ISSUE THREAD

**Issue by nakaz** [jcarreon808/express-gallery#23]
ONE. Modularize your `scss` for better organization and readability. Monolithic stylesheets are never fun... 

For example: 

``` scss
/*header.scss*/
nav {
  /* styles here */

  @media queries {
    /* styles here */
  }
}

/*picture.scss */
.picture {
  /* styles here*/
  @media queries {
    /* styles here */
  }
}

/* and so forth */
```

TWO: Empty selectors are ironically a waste of space (and time) 

if you're leaving them like that because you know you will be adding styles to those selectors, thats fine. but if you're just targeting one single thing and that thing only. target the children directly.

https://developer.mozilla.org/en-US/docs/Web/CSS/Child_selectors

https://github.com/jcarreon808/express-gallery/blob/master/sass/styles.scss#L553

instead of

``` #picturesContainer{
    ul{
      li{
        a{
          img{
            width:300px;
          }
        }
      }
    }
  }
```

try do 

``` scss
#picturesContainer > ul > li > a > img {
  width: 300px; 
}
```

THREE: Naming your elements and selectors

Good practices for naming elements in html/css is not camel case like Javascript ex. `picturesContainer` but rather hyphen-case style `pictures-container`. 

This is important to know because in `scss` we are able to target selectors differently by doing something like `.container__box` or `.container--center` -- something you will get into in the later future. Hyphen case is what stylesheets use for best practice naming schemes. 

example: 

``` scss
.picture-container {
  display: whatever
}
```

the future scss example: 

``` scss
.container {
  display: block;
  &--center {
    text-align: center;
  }
  &__box {
    color: blueish;
  }
}
```
